### ISSUE TITLE
Requested 'libnma >= 1.8.0' but version of libnma is 1.1.93

### ISSUE THREAD

**Issue by viv81ster** [nm-l2tp/NetworkManager-l2tp#107]
Hi 

I tried to install the network manager on Ubuntu 16.04
But I get this issue after ./autogen.sh

```
configure: error: Package requirements (libnma >= 1.8.0) were not met:

Requested 'libnma >= 1.8.0' but version of libnma is 1.1.93

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBNMA_CFLAGS
and LIBNMA_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by dkosovic** [comment]
The master branch needs NetworkManager >= 1.8.0 as it uses features introduced with that version.

For Ubuntu 16.04, i would recommend using the nm-1-2 branch, i.e. :
```
git checkout nm-1-2
```

Main difference between nm-1-2 and master branch is that the master branch has support for user and machine certificates, it also need OpenSSL >= 1.1.0 which Ubuntu 16.04 updates doesn't provide.

**Comment by dkosovic** [comment]
There are build instruction for Ubuntu here :
* https://github.com/nm-l2tp/NetworkManager-l2tp/wiki/Building

**Comment by dkosovic** [comment]
You should also do a `sudo apt update` followed by a `sudo apt upgrade` to upgrade to NetworkManager 1.2.6 as the nm-1-2 branch needs NetworkManager >= 1.2.
