### ISSUE TITLE
How do we import L2TP VPN profiles?

### ISSUE THREAD

**Issue by leftyfb** [nm-l2tp/NetworkManager-l2tp#114]
Now that you've removed the import feature, how do we import L2TP profiles? You mention "didn't provide anything that the saved connections stored in `/etc/NetworkManager/system-connections` did not provide.". 

If this is saying we can just copy conf files directly to the system-connections directory, we still need to generate unique UUID's for those connections. Is there documentation somewhere on how to do this?

Or, if there's another way to import/create L2TP VPN profiles from the command-line, can you link to documentation for it?

https://github.com/nm-l2tp/NetworkManager-l2tp/commit/375bfb8ab6a37461224bd81d2df3581f298cb943#diff-ba222b3b8656f7bd1ab7b0fba8a483e9R95

**Comment by dkosovic** [comment]
If a profile is copied into `/etc/NetworkManager/system-connections/`, a corresponding UUID connection will be generated once NetworkManager is restarted. I believe the following should do it on most linux distros.
```sh
sudo systemctl restart NetworkManager.service
```

Alternatively, If you are configuring a VPN conection for a headless server, as long as it has the GNOME dependencies installed (the server doesn't need to have a X11 server installed, only the client does) you can use X11 SSH tunnelling, e.g.:

```sh
ssh -X username@vpn-server-hostname
nm-connection-editor
```

**Comment by dkosovic** [comment]
My suggestion of restarting the NetworkManager service to detect new VPN connection profile files or changes to those files might be a little too drastic, the following should be enough:
```sh
sudo nmcli con reload
```

Extract from:
* https://developer.gnome.org/NetworkManager/stable/nm-settings-keyfile.html

> Users can create or modify the keyfile connection files manually, even if that is not the 
> recommended way of managing the profiles. However, if they choose to do that, they
>  must inform NetworkManager about their changes (see _monitor-connection-file_ in
> nm-settings(5) and `nmcli con (re)load)`.
