### ISSUE TITLE
any plans on CentOS 8

### ISSUE THREAD

**Issue by victor0801x** [nm-l2tp/NetworkManager-l2tp#115]
Hi, recently I update my laptop to CentOS 8 but cannot find `NetworkManager-l2tp` & `NetworkManager-l2tp-gnome`
it works fine on CentOS 7.x

**Comment by dkosovic** [comment]
Just a minor correction, it was never in the CentOS 7 repositories, but in EPEL7. Similarly with the EPEL8 repository:
   https://apps.fedoraproject.org/packages/NetworkManager-l2tp

According to that page, it was only migrated from testing to EPEL8 18 hours ago, so you might be using an EPEL8 repo that hasn't sync'ed up yet.

**Comment by dkosovic** [comment]
Correction, NetworkManager-l2tp 1.2.14-1.el8 has been in EPEL8 for some time, but version 1.2.16 was only migrated from testing 18 hours ago.

So I suspect you haven't added the EPEL8 repo:
```
sudo dnf install epel-release
```

**Comment by victor0801x** [comment]
thanks for quick reply @dkosovic, you are right, I have installed epel8 long time ago, but forget enable ...
