### ISSUE TITLE
Version 1.8.0 work on Ubuntu not Fedora

### ISSUE THREAD

**Issue by tpimont** [nm-l2tp/NetworkManager-l2tp#117]
Hi,

I setup a L2TP IPSEC connection to a windows server with certificates.
with the last version 1.8.0 on ubuntu 18.04 connection is OK .
I use same parameters on Fedora but on Fedora 31 or 32 the connection fail with this in logs :

pppd[4513]: Plugin /usr/lib64/pppd/2.4.7/nm-l2tp-pppd-plugin.so loaded.
 pppd[4513]: pppd 2.4.7 started by root, uid 0
 pppd[4513]: Using interface ppp0
 pppd[4513]: Connect: ppp0 <--> /dev/pts/1
 NetworkManager[934]: <info>  [1578919319.3271] manager: (ppp0): new Ppp device (/org/freedesktop/NetworkManager/Devices/9)
 NetworkManager[4511]: xl2tpd[4511]: control_finish: Connection closed to X.X.X.144, serial 1 ()
 pppd[4513]: Terminating on signal 15
 pppd[4513]: Modem hangup
 pppd[4513]: Connection terminated.
 NetworkManager[4511]: xl2tpd[4511]: death_handler: Fatal signal 15 received
 charon[4474]: 14[KNL] interface ppp0 deleted
 NetworkManager[934]: <warn>  [1578919319.3408] vpn-connection[0x559d3a83c2e0,ad5560a9-b9f9-44a9-a07f-3a4aa7d14351,"VPN 1",0]: VP>
 NetworkManager[934]: <info>  [1578919319.3409] vpn-connection[0x559d3a83c2e0,ad5560a9-b9f9-44a9-a07f-3a4aa7d14351,"VPN 1",0]: VP>
 NetworkManager[4518]: Stopping strongSwan IPsec...

Any idea ?

**Comment by dkosovic** [comment]
As it looks like something is going wrong with pppd, have a look at the "Increase Debugging Output" section in in the [README.md](https://github.com/nm-l2tp/NetworkManager-l2tp/blob/master/README.md#increase-debugging-output) file. The increased pppd debugging output will be in the journalctl output.

Hopefully the increased debugging output might give us an idea as to what is going wrong.

**Comment by tpimont** [comment]
it works 1 time on 10 try, when it works the log is like this 

janv. 14 07:15:14 localhost.localdomain pppd[5118]: Plugin /usr/lib64/pppd/2.4.7/nm-l2tp-pppd-plugin.so loaded.
janv. 14 07:15:14 localhost.localdomain pppd[5118]: pppd 2.4.7 started by root, uid 0
janv. 14 07:15:14 localhost.localdomain pppd[5118]: Using interface ppp0
janv. 14 07:15:14 localhost.localdomain pppd[5118]: Connect: ppp0 <--> /dev/pts/1
janv. 14 07:15:14 localhost.localdomain NetworkManager[937]: <info>  [1579004114.8937] manager: (ppp0): new Ppp device (/org/freedesktop/NetworkManager/Devices/6)
janv. 14 07:15:17 localhost.localdomain pppd[5118]: CHAP authentication succeeded
janv. 14 07:15:19 localhost.localdomain charon[5064]: 15[KNL] 10.32.1.78 appeared on ppp0
janv. 14 07:15:19 localhost.localdomain charon[5064]: 05[KNL] 10.32.1.78 disappeared from ppp0
janv. 14 07:15:19 localhost.localdomain charon[5064]: 09[KNL] 10.32.1.78 appeared on ppp0
janv. 14 07:15:19 localhost.localdomain charon[5064]: 10[KNL] interface ppp0 activated
janv. 14 07:15:19 localhost.localdomain pppd[5118]: local  IP address 10.32.1.78
janv. 14 07:15:19 localhost.localdomain pppd[5118]: remote IP address 10.32.1.1

So CHAP authentication works sometime and sometime not

**Comment by tpimont** [comment]
For the CHAP authentication to work  
First stop xl2tpd service. 
Then try a connection failed.
Try another connection OK.
All other connection failed until you stop xl2tpd another time

**Comment by dkosovic** [comment]
It might not be the original CHAP, MS-CHAPv2 is typically the one that produces the "CHAP authentication succeeded" pppd output. In the PPP settings dialog box, could you try disabling all the authentication methods other than MSCHAPv2. Some VPN servers claim they support more than MS-CHAPv2 but haven't been configured properly for the other authentication methods.

Fedora's default is for the system xl2tpd service to be disabled and not running, while Ubuntu has it enabled and running. NetworkManager-l2tp starts its own instance of xl2tpd and will kill its own instance when the connection goes down or hasn't been established. See "Issue with not stopping system xl2tpd service" in the README.md file. It might not be the original CHAP, MS-CHAPv2 is typically the one that produces the "CHAP authentication succeeded" pppd output. In the PPP settings dialog box, could you try disabling all the authentication methods other than MSCHAPv2. Some VPN servers claim they support more than MS-CHAPv2 but haven't been configured properly for the other authentication methods.

Fedora's default is for the system xl2tpd service to be disabled and stopped, while Ubuntu has it enabled and running. NetworkManager-l2tp starts its own instance of xl2tpd and will kill its own instance when the connection goes down or hasn't been established. See "Issue with not stopping system xl2tpd service" in the [README.md](https://github.com/nm-l2tp/NetworkManager-l2tp#issue-with-not-stopping-system-xl2tpd-service) file. I would recommend sticking to the Fedora default of having the system xl2tpd service disabled, otherwise an ephemeral port (i.e. random high port) will be used as mentioned in the README.md file.

I've noticed there are a lot of VPN server and/or firewalls out there that will unfortunately block a L2TP client if it is using an ephemeral port on the client side, yet will accept an L2TP connection that is not encapsulated in IPsec which is more important.

**Comment by tpimont** [comment]
all my tests have been done with only  mschap-v2 method in settings .
I have not found a solution that works for now.

**Comment by dkosovic** [comment]
If the system xl2tpd service isn't running, the only other thing I could think of is the kernel. Some kernel updates in the past have broken xl2tpd.

Last night I installed Fedora 31 in a VM and did a `sudo dnf update` to get the latest packages and haven't been able to reproduce the issue. So it might not be an issue with the latest kernel, but no harm in trying an older kernel.

**Comment by tpimont** [comment]
It's like when you untick all ppp authentication except mschap-v2 , ppp continue to use CHAP .
can you add a option to refuse-chap in the PPP settings ?

**Comment by tpimont** [comment]
In the Windows server log with Fedora client i have this event : Remoteaccess eventid 20262 Cannot reconize initial frame line has been disconnect.
Error description is : Check the credentials of the remote access client .
Login and password are good 
there is something wrong with ppp authentication in Fedora but i dont no what is wrong

**Comment by dkosovic** [comment]
It you enable debugging mode as described in the [README.md](https://github.com/nm-l2tp/NetworkManager-l2tp/blob/master/README.md) file, the run-time generated `/var/run/nm-l2tp-`_UUID_`/ppp-options` file won't get deleted. (note: replace UUID with the actual UUID used in the filesname). Can you confirm if an authentication types is disabled in the PPP settings dialog box, then you see the corresponding `refuse-` option in the generated ppp-options file like it should be?

You can see the `refuse-` authentication options that are handled in the following section of the source code:
* https://github.com/nm-l2tp/NetworkManager-l2tp/blob/master/src/nm-l2tp-service.c#L499

The Fedora pppd package has lots Fedora patches :
* https://src.fedoraproject.org/rpms/ppp/tree/f31

ppp also uses PPP kernel modules.

So although the ppp version number is the same as on Ubuntu, perhaps some patch only applied on Fedora  is the problem or a kernel module in a later kernel might have broken something.

**Comment by tpimont** [comment]
content of the file ppp-options in /var/run/nm-l2tp-UUID/ :
debug
ipparam nm-l2tp-service-xxxx
nodetach
usepeerdns
noipdefault
nodefaultroute
noauth
noccp
refuse-eap
lcp-echo-failure 5
lcp-echo-interval 30
plugin /usr/lib64/pppd/2.4.7/nm-l2tp-pppd-plugin.so
mru 1400
mtu1400

**Comment by tpimont** [comment]
content of the file ppp-options:
debug
ipparam nm-l2tp-service-xxxxxxxxxxx
nodetach
usepeerdns
no ipdefault
nodefaultroute
noauth
refuse-eap
refuse-pap
refuse-chap
refuse-mschap
lcp-echo-failure 5
lcp-echo interval 30
plugin /var/lib64/pppd/2.4.7/nm-l2tp-pppd-plugin.so
mru 1400
mtu 1400

**Comment by dkosovic** [comment]
I setup RRAS on Windows Server 2019 and was able to reproduce the issue with Fedora 31.

I see the following error in the xl2tpd logs:
```
xl2tpd[2727]: L2TP kernel support not detected (try modprobing l2tp_ppp and pppol2tp)
```

then trying to do what it suggests:
```
$ sudo modprobe l2tp_ppp

$ sudo modprobe pppol2tp
modprobe: FATAL: Module pppol2tp not found in directory /lib/modules/5.4.8-200.fc31.x86_64
```

Not sure why the pppol2tp kernel module is missing.

So I'm guessing the VPN is working for you on Ubuntu as you are using Linux kernel PPP over L2TP instead of the userspace fallback implementation that you are using on Fedora with xl2tpd.

It is interesting how it breaks with Win2019, but not other VPN servers.

**Comment by tpimont** [comment]
Glad to see that you can reproduce the issue, thanks for your help.
i'm searching if i can find a solution with the module on Fedora

**Comment by dkosovic** [comment]
pppol2tp module might not be the issue as I see the following on Ubuntu 18.04 :
```
$ sudo modprobe pppol2tp
modprobe: FATAL: Module pppol2tp not found in directory /lib/modules/4.15.0-74-generic
```

**Comment by dkosovic** [comment]
After doing `sudo modprobe l2tp_ppp` on Fedora, I'm able to make a VPN connection.

Actually Ubuntu 18.04 doesn't have the `L2TP kernel support not detected (try modprobing l2tp_ppp and pppol2tp)` xl2tpd error, even though `sudo modprobe pppol2tp` failed.

Interestingly Ubuntu kernel was configured for PPPOL2TP :
```
$ grep CONFIG_PPPOL2TP /boot/config-4.15.0-74-generic
CONFIG_PPPOL2TP=m
```

Similarly for Fedora:
```
 grep CONFIG_PPPOL2TP /boot/config-5.4.8-200.fc31.x86_64
CONFIG_PPPOL2TP=m
```

**Comment by dkosovic** [comment]
On Fedora `/usr/lib/systemd/system/xl2tpd.service` has the following line:
```
ExecStartPre=/sbin/modprobe -q l2tp_ppp
```
but in this case, xl2tpd isn't started as a service, so `l2tp_ppp` kernel module isn't loaded.

Debian/Ubuntu doesn't  do a modprobe l2tp_ppp in `/etc/init.d/xl2tpd`.  I'm not sure how `l2tp_ppp` kernel module is automatically loaded on Debian/Ubuntu.

**Comment by tpimont** [comment]
Hi,
I confirm that on Fedora when i do a sudo modprobe l2tp_ppp, vpn works .
Thank you for your help

**Comment by dkosovic** [comment]
Looks like kernel 5.4.8 partly broke xl2tpd (although it might have been an earlier kernel 5.4 version) that broke the `l2tp_ppp` kernel module from being automatically loaded. When the older kernel 5.3.7 was used, xl2tpd outputs "Using l2tp kernel support" as shown below just after the kernel outputs `l2tp_core` and `l2tp_netlink` messages.

**kernel-5.3.7-301.fc31** :
```
Jan 20 19:47:23 localhost.localdomain nm-l2tp-service[2184]: xl2tpd started with pid 2891
Jan 20 19:47:23 localhost.localdomain NetworkManager[793]: <info>  [1579513643.0655] vpn-connection[0x563cebc240a0,56003fee-4183-44f4-ba9f-a8e21e3f12f6,"Work",0]: VPN plugin: state changed: starting (3)
Jan 20 19:47:23 localhost.localdomain NetworkManager[793]: xl2tpd[2891]: Not looking for kernel SAref support.
Jan 20 19:47:23 localhost.localdomain kernel: PPP generic driver version 2.4.2
Jan 20 19:47:23 localhost.localdomain kernel: NET: Registered protocol family 24
Jan 20 19:47:23 localhost.localdomain kernel: l2tp_core: L2TP core driver, V2.0
Jan 20 19:47:23 localhost.localdomain kernel: l2tp_netlink: L2TP netlink interface
Jan 20 19:47:23 localhost.localdomain NetworkManager[793]: xl2tpd[2891]: Using l2tp kernel support.
```


**kernel-5.4.8-200.fc31** :
```
Jan 20 19:54:49 localhost.localdomain nm-l2tp-service[1972]: xl2tpd started with pid 2058
Jan 20 19:54:49 localhost.localdomain NetworkManager[746]: <info>  [1579514089.6735] vpn-connection[0x563cebc240a0,56003fee-4183-44f4-ba9f-a8e21e3f12f6,"Work",0]: VPN plugin: state changed: starting (3)
Jan 20 19:54:49 localhost.localdomain NetworkManager[746]: xl2tpd[2058]: Not looking for kernel SAref support.
Jan 20 19:54:49 localhost.localdomain kernel: PPP generic driver version 2.4.2
Jan 20 19:54:49 localhost.localdomain kernel: NET: Registered protocol family 24
Jan 20 19:54:49 localhost.localdomain NetworkManager[746]: xl2tpd[2058]: L2TP kernel support not detected (try modprobing l2tp_ppp and pppol2tp)
```

Might need to lodge a Fedora bug.

**Comment by dkosovic** [comment]
Closing this issue as I've submitted the following bug reports :
* **Fedora 31** -  https://bugzilla.redhat.com/show_bug.cgi?id=1794886
* **RHEL 8.1** -  https://bugzilla.redhat.com/show_bug.cgi?id=1794886

xl2tpd is suppose to auto-load the `l2tp_ppp` kernel module by opening a PPPoX socket, i.e. doing  `socket(AF_PPPOX, SOCK_DGRAM, PX_PROTO_OL2TP)` :
* https://github.com/xelerance/xl2tpd/blob/master/network.c#L113

Which amongst other things, does the equivalent of  `modprobe net-l2tp-type-7` and that is what I believe is broken, note that net-l2tp-type-7 is an alias of l2tp_ppp :
```
$ modinfo l2tp_ppp | grep alias
alias:          net-l2tp-type-7
alias:          net-pf-24-proto-1
```
e.g. on Fedora 31 and RHEL 8.1 where it doesn't do the right thing :
```
$ sudo modprobe net-l2tp-type-7

$ lsmod | grep l2tp
```

On Fedora 30 where it works:
```
$ sudo modprobe net-l2tp-type-7

$ lsmod | grep l2tp
l2tp_ppp               32768  0
l2tp_netlink           28672  1 l2tp_ppp
l2tp_core              36864  2 l2tp_ppp,l2tp_netlink
pppox                  16384  1 l2tp_ppp
ip6_udp_tunnel         16384  1 l2tp_core
udp_tunnel             16384  1 l2tp_core
ppp_generic            49152  2 pppox,l2tp_ppp
```

The same `l2tp_ppp` kernel module not auto-loading issue appears in https://github.com/xelerance/xl2tpd/issues/188

**Comment by dkosovic** [comment]
The following is an extract from _"Enhanced security of auto-loading kernel modules in RHEL 8 "_  web page (which requires a login to view) :
* https://access.redhat.com/articles/3760101

> To enhance Red Hat Enterprise Linux against possible future security vulnerabilities in lesser-known components which system administrators typically do not protect against, a set of kernel modules have been moved to the `kernel-modules-extra` package so they are not installed by default, and blacklisted by default so those components cannot be loaded by non-root users.
> 
> When a system requires use of one of these kernel modules, the system administrator must install the `kernel-modules-extra` package and explicitly remove the module blacklist.

Although the above was for RHEL8, it is also applicable to Fedora >= 31.
The `/etc/modprobe.d/l2tp_netlink-blacklist.conf` file contains:
```sh
# Remove the blacklist by adding a comment # at the start of the line.
blacklist l2tp_netlink
```

The `/etc/modprobe.d/l2tp_ppp-blacklist.conf` file contains :
```sh
# Remove the blacklist by adding a comment # at the start of the line.
blacklist l2tp_ppp
```

To remove the blacklist of the L2TP modules by adding a # comment to the blacklist lines can be achieved with:
```
sudo sed -e '/blacklist sctp/s/^b/#b/g' -i /etc/modprobe.d/l2tp_netlink-blacklist.conf
sudo sed -e '/blacklist sctp/s/^b/#b/g' -i /etc/modprobe.d/l2tp_ppp-blacklist.conf
```
