### ISSUE TITLE
Disconnect after a few minutes

### ISSUE THREAD

**Issue by cprog** [nm-l2tp/NetworkManager-l2tp#118]
Hello,
I use Arch Linux . .
Using NetworkManager-l2tp  I setup L2TP with preshared  key..
My settings are:

Phase 1 algorithms: 3des-sha1-modp1024
Phase 2 algorithms: 3des-sha1
Authentication: MSCHAP && MSCHAP2

 ipsec --version
Linux Libreswan 3.29 (netkey) on 5.4.14-arch1-1

System xl2tpd is disabled.

When I run `sudo /usr/lib/NetworkManager/nm-l2tp-service --debug` I see this error:

```
xl2tpd[51626]: Can not find tunnel 22 (refhim=0)
xl2tpd[51626]: network_thread: unable to find call or tunnel to handle packet.  call = 0, tunnel = 22 Dumping.
xl2tpd[51626]: Can not find tunnel 22 (refhim=0)
xl2tpd[51626]: network_thread: unable to find call or tunnel to handle packet.  call = 0, tunnel = 22 Dumping.
xl2tpd[51626]: Can not find tunnel 22 (refhim=0)
xl2tpd[51626]: network_thread: unable to find call or tunnel to handle packet.  call = 0, tunnel = 22 Dumping.
xl2tpd[51626]: Maximum retries exceeded for tunnel 13568.  Closing.
xl2tpd[51626]: Terminating pppd: sending TERM signal to pid 51627
```

**Comment by dkosovic** [comment]
Sorry I'm not sure. I vaguely remember seeing similar error output and it was related to broken routing.

**Comment by cprog** [comment]
Thank you @dkosovic  for your reply.
The problem was that on the router has a second L2TP IPSEC connection(second account)  to the same server.
In other words you can't have VPN on the router and behind him in the same time .
