### ISSUE TITLE
Unable to save password

### ISSUE THREAD

**Issue by stdex** [nm-l2tp/NetworkManager-l2tp#126]
Hello.

This problem marked in wiki as "fixed":
https://github.com/nm-l2tp/NetworkManager-l2tp/wiki/Known-Issues#unable-to-save-password

But I can't confirm this. 
In my case, if I use mode "Request this password every time" and try to connect - this not working, a window with a choice of a password is not displayed, in log I can see message: "Invalid VPN service type (cannot find authentication binary)".

This problem is definitely not related to l2tp, I find simalair mark about it in openvpn (https://necromuralist.github.io/posts/openvpn-on-ubuntu-1804/), but I would like to find solution without save password or use nm-applet as connection manager. Could you please confirm the existence of such a problem at the moment with you?

My configuration:
Ubuntu 20.04
Linux 5.4.0-18-generic
GNOME Shell 3.35.91
network-manager 1.22.10-1ubuntu1
network-manager-l2tp 1.2.16-1
network-manager-l2tp-gnome 1.2.16-1

**Comment by dkosovic** [comment]
I've just installed the latest Ubuntu 20.04 focal-desktop-amd64.iso in a VM. I'm not able to reproduce the issue.

I'm not running `nm-applet`, but am running the same version of `gnome-shell` as you.

I've also tested using the `nmcli` command line, in the below the `id` can be found by looking at the output of  `nmcli con`.


**1.** test connection with "Request this password every time" set : 

```
$ nmcli con up id "Test VPN"
You need to authenticate to access the Virtual Private Network 'EAIT VPN'.
Warning: password for 'vpn.secrets.password' not given in 'passwd-file' and nmcli cannot ask without '--ask' option.

Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/1)
```
A dialog box popped up asking for the password.

**2.** test connection with "Request this password every time" set and `--ask` command-line switch :

```
$ nmcli con up id "TEST VPN" --ask
You need to authenticate to access the Virtual Private Network 'EAIT VPN'.
Password: (vpn.secrets.password): •••••••••••••••
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/2)
```

**3.** test connection with "Store the password for all users" set :
```
$ nmcli con up id "Test VPN"
Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/3)

```

**Comment by dkosovic** [comment]
The GNOME Secret Service is used to store the password. Could you try using `secret-tool` to do a lookup of the password using the VPN connection's UUID and see if you get any Secret Service error.

```
$ nmcli con
NAME                UUID                                  TYPE      DEVICE 
Wired connection 1  f0a21a1d-d96d-3bf9-8e59-230f682c03c2  ethernet  ens33  
Test VPN            e7102e5e-8b0c-4f18-8a14-02c18943d0b3  vpn       -- 
```

```
$ secret-tool lookup connection-uuid e7102e5e-8b0c-4f18-8a14-02c18943d0b3
this-is-the-actual-password
```

**Comment by stdex** [comment]
Yes, after restart it started to work for me too.  
I do not know what this may be connected with, possibly with the update gnome.
