### ISSUE TITLE
Automaticallz reconnect when connection is lost

### ISSUE THREAD

**Issue by cristobaltapia** [nm-l2tp/NetworkManager-l2tp#129]
Hi,

I have configured the VPN successfully and can connect to the VPN of my workplace. However, after a minute or so the connection is lost and have to manually reconnect. Is it there an option to automatically reconnect in such a case? I have searched for it, but could not find anything that would work for me.

**Comment by dkosovic** [comment]
You could use a script that makes use of the NetworkManager command-line interface, i.e. the `nmcli` command. For your refrence, common `nmcli` commands are:

* list all NM connections: `nmcli con`
* bring up VPN connection : `nmcli con up id VPN-Connection-Name`
* bring down VPN connection: `nmcli con down id VPN-Connection-Name`

Have a look at the following script, it should do what you want:
* https://gist.github.com/numericOverflow/b2d16459158a671abbb36372620c1679

Should only need to change `VPN_UID`, `LOG` and `CHECK_HOST` in that script.

**Comment by cristobaltapia** [comment]
Thanks for that! I will try it.
