### ISSUE TITLE
Improve support for routes without gateway address

### ISSUE THREAD

**Issue by puleglot** [nm-l2tp/NetworkManager-l2tp#133]
I can add routes without a gateway by entering `0.0.0.0` in a gateway address field. However if I open the preference dialog again, the gateway fields are empty end highlighted in red.

![Снимок экрана от 2020-03-31 22-27-39](https://user-images.githubusercontent.com/5680903/78067193-f7582f00-739e-11ea-8a28-467241e62d01.png)

**Comment by dkosovic** [comment]
I'm able to reproduce that `0.0.0.0` gateway roue issue with other NetworkManager VPN implementations, not just l2tp. i also tested up to NetworkManager 1.22.10 and it is still an issue.

As the IPv4 settings tab is managed by NetworkManager, not the VPN implementations, it would probably be best to report the bug to the GNOME Project's NetworkManager [BugTracker](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/issues) link on the following page :

* https://wiki.gnome.org/Projects/NetworkManager

**Comment by puleglot** [comment]
Looks like this was fixed in the latest stable releases of networkmanager. I cannot reproduce this with 1.18.6

**Comment by dkosovic** [comment]
This GNOME Control Center bug was fixed with commit https://github.com/GNOME/gnome-control-center/commit/a73ae5ddae400aae2392aa7d4b98eafc81e77a17 as reported in the following bug report:

* https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1055
