### ISSUE TITLE
"Disable PFS" problem 

### ISSUE THREAD

**Issue by romulogcerqueira** [nm-l2tp/NetworkManager-l2tp#142]
On IPsec settings, I check the "Disable PFS" tick box, however, this configuration is not stored. How can I overcome this issue?

I am using Ubuntu 20.04.

**Comment by dkosovic** [comment]
The "Disable PFS" option is disabled if detects strongswan. PFS for strongSwan 5.x onwards is enabled by appending a DH group to the ESP (i.e. phase 2 algorithms) settings, see:
* https://wiki.strongswan.org/projects/strongswan/wiki/SecurityRecommendations

So I assume you are using libreswan.

If you run `/usr/bin/nm-connection-editor`, tick the "Disable PFS" check box, save the connection, then re-open the connection, is the "Disable PFS" check box still enabled?

If you are using KDE plasma-nm that comes with Kubuntu 20.04, it will erase "Disable PFS" the setting, you would need to use a newer version of plasma-nm that has the "Disable PFS" check box, e.g.:

![plasma-nm L2TP](https://camo.githubusercontent.com/809992ff1f1129361f43c2ef3d4d436bd87cf98a/68747470733a2f2f7068616272696361746f722e6b64652e6f72672f66696c652f646174612f37683565686b77647a75636f65647576746177672f504849442d46494c452d7a796d6374626a6b706b6d6666707172337074322f6e65772d6c3274702d69707365632d322e706e67)

**Comment by dkosovic** [comment]
If you are using KDE plasma-nm on Kubuntu 20.04, the following thread describes a workaround to stop "Disable PFS" option being removed by changing permissions of the config file:
* https://forum.kde.org/viewtopic.php?f=18&t=163029

I'm closing this issue due to lack of response activity. I will reopen if there are responses.
