### ISSUE TITLE
KDE support

### ISSUE THREAD

**Issue by tpimont** [nm-l2tp/NetworkManager-l2tp#148]
Hi,

It is not really an issue, but is there a way to add Network Manager l2tp machine certificate support for KDE ?
In KDE the plugin only support user certificates not machine.

Thanks

**Comment by dkosovic** [comment]
You need plasma-nm 5.19 or later which has machine certificate support:
![IPsec config certificate](https://phabricator.kde.org/file/data/7h5ehkwdzucoeduvtawg/PHID-FILE-zymctbjkpkmffpqr3pt2/new-l2tp-ipsec-2.png)

**Comment by tpimont** [comment]
I try with kubuntu 20.10 with plasma 5.19 but i dont see this, only PSK .
I will try another time with kubuntu 20.10 an install nm-l2tp with certificates support

**Comment by tpimont** [comment]
I can confirm that  with an installed version of Kubuntu 20.10 daily 18092020, Kde Network Manager have L2tp machine certificates support.
Thanks for your help .

**Comment by dkosovic** [comment]
Glad to hear you resolved it.

If you ever want an Ubuntu 20.04 based Linux distribution with the latest stable KDE support (from KDE themselves), I would recommend KDE neon User Edition :
* https://neon.kde.org/download

**Comment by dkosovic** [comment]
Forgot to mention I haven't made a network-manager-l2tp 1.8.2 package which has certificate support for Ubuntu 20.10 yet:
* https://launchpad.net/~nm-l2tp/+archive/ubuntu/network-manager-l2tp-certificate

Ubuntu doesn't consider OpenSSL to be a system library, so it would be a violation to link GPL'ed code against versions of OpenSSL < 3.0.0. Those launchpad network-manager-l2tp 1.8.2 packages are statically linked against alpha version of OpenSSL. Ubuntu doesn't allow statically linked packages, but it is okay for launchpad packages.

So for the time being, you will probably need to build network-manager-l2tp 1.8.2 from source code.
