### ISSUE TITLE
This is more of a thanks than an issue!!!!

### ISSUE THREAD

**Issue by PROBLEMCHYLD** [nm-l2tp/NetworkManager-l2tp#149]
I wanted to say thank you very much for your hard work. You have made my Linux experience better with these tools. I have tested both PSK and TLS Certificates with strongswan 5.9.0 on Slackware Linux 14.2 and I have no problems with any connections. It has been a couple of months of success.

**Comment by dkosovic** [comment]
I like this issue that isn't an issue and glad to hear you have no problems with any connections. I sincerely appreciate your kind comments.
