### ISSUE TITLE
Libreswan server

### ISSUE THREAD

**Issue by pawel-zajac90** [nm-l2tp/NetworkManager-l2tp#152]
Hello once again ;)
my client and server os is ubuntu 20.04
i'd like to connect to server based on Libreswann with network-manager-l2tp, but it's using strongswan.
Is this correct way?
1. Install network-manager-l2tp & network-manager-l2tp-gnome
2. Uninstall Strongswan with all plugins
3. Install libreswan

I'm using this configuration: https://github.com/hwdsl2/setup-ipsec-vpn

**Comment by dkosovic** [comment]
libreswan or strongswan clients should be compatible with a strongswan server, if it doesn't work it is a bug.

the `network-manager-l2tp` package has a dependency on `(strong | libreswan)`, i.e. either will satisfy the dependency, 

If you haven't installed libreswan or network-manager-l2tp* packages, you could issue:
```
sudo apt install network-manager-l2tp-gnome libreswan
```
or 
```
sudo apt install libreswan
sudo apt install network-manager-l2tp-gnome
```

you could optionally add, `network-manager-l2tp`, but is redundant as it is a dependency of `network-manager-l2tp-gnome`.


If you have already installed network-manager-l2tp and strongswan, you can issue the following which will automatically uninstall the main strongswan package while installing libreswan:

```
sudo apt install libreswan
```

You could then optionally remove and remaining strongswan packages.

**Comment by pawel-zajac90** [comment]
i had network-manager-l2tp installed
so i just installed libreswan...and now none vpn works...

**Comment by dkosovic** [comment]
If none of your VPN connection now work, I would need to see some log output, e.g. `journalctl --unit=NetworkManager` see the Debugging section of the README.md file for more debugging details:
* https://github.com/nm-l2tp/NetworkManager-l2tp

**Comment by dkosovic** [comment]
If you didn't allow the libreswan package to replace `/etc/ipsec.conf` with its own copy, you probably have a broken `/etc/ipsec.conf` for libreswan.

You could purge `/etc/ipsec.conf` and reinstall with:

```
sudo apt-get purge libreswan network-manager-l2tp network-manager-l2tp-gnome
sudo apt install network-manager-l2tp-gnome libreswan
```

**Comment by pawel-zajac90** [comment]
I did replaced it, but there was pluto isue, i will start with it one more time in two-three hours, and i will let You know :)

**Comment by dkosovic** [comment]
I'll close this issue, if you still have an issue, I will re-open this issue if needed when you reply.
