### ISSUE TITLE
Document connection profile properties

### ISSUE THREAD

**Issue by kevinoid** [nm-l2tp/NetworkManager-l2tp#155]
I'm new to NetworkManager-l2tp and couldn't find any documentation for what connection profile properties are available or how to configure them.  For example, something similar to [`nm-settings(5)`](https://manpages.debian.org/nm-settings.5) or the [Configuration Settings chapter of the Network Manager Reference Manual](https://developer.gnome.org/NetworkManager/stable/ref-settings.html).  Does such documentation exist?

Thanks,
Kevin

**Comment by dkosovic** [comment]
There isn't any such documentation, but you can find the list of properties here:
* https://github.com/nm-l2tp/NetworkManager-l2tp/blob/master/shared/nm-service-defines.h

and the type of each property here:
* https://github.com/nm-l2tp/NetworkManager-l2tp/blob/master/src/nm-l2tp-service.c#L149

**Comment by kevinoid** [comment]
Good to know.  Those will be very helpful.  Thanks @dkosovic!
