### ISSUE TITLE
Version mismatch causing inability to connect to l2tp tunnels

### ISSUE THREAD

**Issue by birdiesanders** [nm-l2tp/NetworkManager-l2tp#156]
Arch has supplied version 2.4.8 of network-manager, and upon connection, it complains about the plugin being built for 2.4.7, and it then kills the process and refuses to connect. 

```
 Plugin /usr/lib/pppd/2.4.7/nm-l2tp-pppd-plugin.so is for pppd version 2.4.7, this is 2.4.8
```

**Comment by dkosovic** [comment]
That's an issue with pppd, there are upstream bug reports for a way to query for pppd plugin directory, e.g. :
* https://github.com/paulusmack/ppp/issues/19
* https://github.com/paulusmack/ppp/pull/47

I notice with the Arch `PKGBUILD` file for networkmanager-pptp it does :

```sh
_pppver=2.4.8
depends=(... "ppp=$_pppver" ...)

 ./configure ... \
    --with-pppd-plugin-dir=/usr/lib/pppd/$_pppver
```

Some other linux distros do something like the following so as not to hardcode the pppd version at build time:

```
_pppver=`sed -n 's/^\#define\s*VERSION\s*"\([^\s]*\)"$$/\1/p' /usr/include/pppd/patchlevel.h`
```

**Comment by birdiesanders** [comment]
Hmmm, interesting. I think I may take a crack at modifying the pkgbuild for that in this way and see if this works. If it fixes it, I may just have to submit a patch!

**Comment by birdiesanders** [comment]
Well, on a cursory look, it appears that I never had that package installed. Now I have no idea of anything.

**Comment by dkosovic** [comment]
I think the Arch network-manager-l2tp package was moved to a community package today

**Comment by birdiesanders** [comment]
It seems they pushed the packages after I had updated, just needed to wait a few hours... Thanks for your help though, I appreciate you taking the time.

**Comment by birdiesanders** [comment]
I am not sure that package is in community yet, fyi.

**Comment by dkosovic** [comment]
Indeed. I remembered reading an AUR networkmanager-l2tp comment about migrating to community, then incorrectly made the assumption it had migrated after you mentioned a disappearing package issue.

**Comment by birdiesanders** [comment]
They updated the pkgbuild this morning, and all the components are happy again. I'll close this, as this is 100% not your issue. Again, thanks so much. I hope the weekend is awesome!
