### ISSUE TITLE
VPN L2TP with Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by gmastromatteo** [nm-l2tp/NetworkManager-l2tp#160]
Hi 
i am not able to connect to our meraki cisco with my ubuntu desktop. I've followed the instruction on this page https://documentation.meraki.com/MX/Client_VPN/Client_VPN_OS_Configuration
and 
https://github.com/nm-l2tp/NetworkManager-l2tp#issue-with-not-stopping-system-xl2tpd-service
If requested I can share the logs .
please let me know
thanks to all 
gianni

**Comment by dkosovic** [comment]
I'm guessing it is an issue with the strongSwan Cisco Unity plugin, see:
* https://github.com/nm-l2tp/NetworkManager-l2tp/wiki/Known-Issues#strongswan-no-acceptable-traffic-selectors-found

**Comment by gmastromatteo** [comment]
Hi Douglas and thank you for your feedback.
I'm not using strongswan. Here is what I did to configure my vpn connection
with ubuntu.
I hope it will clarify my request.
thanks
gianni

Il giorno mer 28 apr 2021 alle ore 13:54 Douglas Kosovic <
***@***.***> ha scritto:

**Comment by dkosovic** [comment]
> I'm not using strongswan. Here is what I did to configure my vpn connection with ubuntu. I hope it will clarify my request.

Did you attach something with your email reply? I don't see what you did to configure your VPN connection.

I think I will need the logs, also which Ubuntu version are you using?

I would recommend using the newer version of network-manager-l2tp from:
* https://launchpad.net/~nm-l2tp/+archive/ubuntu/network-manager-l2tp

**Comment by gmastromatteo** [comment]
Hi Douglas
Thank you for your feedback. Using the latest version of l2tp network
manager it’s work fine.
Thank you so much for your quickly support !
Best regards
Gianni

Il giorno gio 29 apr 2021 alle 00:00 Douglas Kosovic <
***@***.***> ha scritto:

**Comment by gmastromatteo** [comment]
Ciao Douglas
to be honest I also followed this procedure coming from the meraki
community. It works fine for my Ubuntu 20.04.2 TLS.
thanks again
best regards
gianni


1. Update and clean up the machine first

sudo apt-get update
sudo apt-get dist-upgrade
sudo reboot# Wait for reboot, log back in
sudo apt autoremove

 2. Install VPN Software

sudo apt-get install strongswan xl2tpd net-tools
sudo apt-get install network-manager-l2tp network-manager-l2tp-gnome
sudo apt-get install network-manager-strongswan
sudo reboot

3. After reboot, Turn off the L2TP Server, we only want the client

sudo service xl2tpd stop
sudo systemctl disable xl2tpd



4. Setup the VPN per @PigMan
<https://community.meraki.com/t5/user/viewprofilepage/user-id/4675>'s
instructions:

   - Settings -> Network -> VPN - > "+"
   - Details:
      - Make available to other users, check (if desired)
   - Identity:
      - Name: Make a description
      - Gateway: the IP address (or dyn dns name from the meraki page)
      - User Name:  ***@***.***
      - Password: Leave blank, will prompt
      - NT Domain: <blank>
   - IPSec Settings:
      - Enable IpSec tunnel to L2TP host: check
      - Pre-Shared Key:  Get from the meraki setup page
      - Phase1 Algorithms: 3des-sha1-modp1024
      - Phase2 Algorithms: aes128-sha1
      - Enforce UDP encap: <un checked>
   - PPP Settings:  Default




Il giorno gio 29 apr 2021 alle ore 06:40 gianni mastromatteo <
***@***.***> ha scritto:

**Comment by dkosovic** [comment]
glad to hear it is working for you.
