### ISSUE TITLE
No DNS in the tunnel

### ISSUE THREAD

**Issue by carlihland** [nm-l2tp/NetworkManager-l2tp#164]
Hello.

I tried setting up Ubuntu 21.04 and the issue with no dns after disconnect is now fixed out of the box. But I cant seem to get any dns in the tunnel. I might have a config issue. Terminal says: Temporary failure in name resolution

Thanks.

Carl

**Comment by carlihland** [comment]
Thank you so much for responding, and it in such a prompt manner! :)

Here is my print from before the tunnel is up:
`carl@carl-MS-7B84:~$ systemd-resolve --status
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: foreign

Link 2 (enp27s0)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 195.50.194.250
       DNS Servers: 195.50.194.250 195.50.194.249
`
And here is after:
`carl@carl-MS-7B84:~$ systemd-resolve --status
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: foreign

Link 2 (enp27s0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (ppp0)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 10.10.57.11
       DNS Servers: 10.10.57.11 10.10.57.12
`
So it does get the correct DNS servers published. But still I get the Temporary failure in name resolution.

`carl@carl-MS-7B84:~$ ping XXXXXX.XXXXXXXXXX.local
ping: XXXXXX.XXXXXXXXXX.local: Temporary failure in name resolution
carl@carl-MS-7B84:~$ 
`

This leads me to think the the problem is not directly related to nm-l2tp, but rather a subsequent failure somewhere. Hm. Kinda stuck. I might revert to LTS for the time being but maybe you want me to keep this system up for now? I'd be happy to assist if needed.

**Comment by carlihland** [comment]
I did the dnsmasq workaround to fix this issue. Thanks!

**Comment by dkosovic** [comment]
Glad to hear you solved the issue by switching to DNSMasq.

I had more info on the wiki for multicast DNS (mDNS) `.local` addresses when trying to resolve `.local` addresses instead as unicast DNS addresses on a remote VPN network :
* https://github.com/nm-l2tp/NetworkManager-l2tp/wiki/Known-Issues#local-hostname-resolution

I might need to update the info when trying not to use mDNS with systemd-resolved over a VPN connection for unicast `.local` addresses. I might suggest to use DNSMasq like your solution.
