### ISSUE TITLE
GUI option for automatically reconnecting on failure?

### ISSUE THREAD

**Issue by jonesmz** [nm-l2tp/NetworkManager-l2tp#172]
I sometimes use networkmanager-l2tp when on an incredibly flakey internet connection. It can cut out for up to a minute on a regular basis.

When that happens, the VPN connection disconnects, and remains disconnected.

I don't see a GUI open for having Network Manager automatically attempt to reconnect.

Is this something that could be added?

**Comment by dkosovic** [comment]
`nm-connection-editor` and some other GUI frontends don't expose the NetworkManager `vpn.persistent` property as a check box. As a workaround you could use  `nmcli` to set it.

To list the VPN connection names :
```
nmcli con show
```

To show all the properties of a connection including  `vpn.persistent` and `connection.autoconnect-retries`, issue:
```
nmcli connection show <connection name>
```

To set  `vpn.persistent` and `connection.autoconnect-retries`, issue:
```
nmcli connection modify <connection name> connection.autoconnect-retries 3
nmcli connection modify <connection name> vpn.persistent yes
```
