### ISSUE TITLE
Is there documentation (or support) for connecting to networks that require MFA/2FA?

### ISSUE THREAD

**Issue by rhodges** [nm-l2tp/NetworkManager-l2tp#178]
I'm the lone Linux user in a Windows/Mac organization, and I rely on your product to connect to the network now that I mostly work remotely. So, first and foremost: THANK YOU! I could not have done my job (doing good non-profit work for the planet and the people on it) during the pandemic without you.

Our IT provider is planning on securing our network using Multi-Factor Authentication. 

* Does NetworkManager-l2tp support MFA/2FA requests?
* If so: is there documentation I can refer to to prepare for this shift?
* If not: are there plans to support it in the future?

**Comment by dkosovic** [comment]
The Windows built-in L2TP client doesn't have native MFA/2FA support, yet it works with L2TP/IPsec servers that provide MFA/2FA, e.g. the Cisco DUO L2TP/IPsec docs :
* https://duo.com/docs/cisco-ipsec

The NetworkManager-l2tp client should work with MFA/2FA if the Windows built-in L2TP client does.

The following thread is in regards to NetworkManager-l2tp working with Cisco DUO MFA :
* https://bbs.archlinux.org/viewtopic.php?id=265865

**Comment by rhodges** [comment]
Thanks @dkosovic -- just as you wrote that I was prompted to test our network MFA again -- I didn't realize the Cisco DUO setup would just send the prompt to my phone as an 'approve/deny': I had expected to be prompted for a 1-time-password sort of thing.

Instead, everything worked super slick! Glad to know I can keep using your great tool!
