### ISSUE TITLE
Error: Unable to load VPN connection editor

### ISSUE THREAD

**Issue by martinmicevski** [nm-l2tp/NetworkManager-l2tp#186]
Hello to all,

I have a problem as Manjaro user to create or edit L2TP connection with the GTK4 based gnome-control-center. I got error **Error: Unable to load VPN connection editor**

![image](https://user-images.githubusercontent.com/24639995/166331728-eacf6f91-5ef0-4aa8-910b-8a6e90a0de68.png)

When I use GTK3 based control center nm-connection-editor, everything is fine.

Can you please update this package to the lates version so everything should be working well on GTK4?

OS: Manjaro Linux x86_64 
Kernel: 5.15.37-1-MANJARO 
DE: GNOME 42.0 

Br,
Martin

**Comment by dkosovic** [comment]
I don't maintain the Manjaro (or Arch Linux) networkmanager-l2tp packages. You will need to submit a request to your Linux distro.

**Comment by dkosovic** [comment]
Arch Linux already has one networkmanager-l2tp bug report, I'm not sure where you submit Manjaro bugs.
