### ISSUE TITLE
2fa support?

### ISSUE THREAD

**Issue by pablogipi** [nm-l2tp/NetworkManager-l2tp#202]
Hello.
I'm trying to connect to a fortinet  VPN.
On windows I use the FortiClient which support 2FA.
On  Linux I only have an option to set user and password, and pre-shared password.
When I try to connect it always fails.
I wonder if NetworkManager-l2tp supports 2 Factor Authentication.
Thanks

**Comment by dkosovic** [comment]
See the following issue where 2FA previously came up:
* [Issue# 178 - Is there documentation (or support) for connecting to networks that require MFA/2FA?](https://github.com/nm-l2tp/NetworkManager-l2tp/issues/178)

I suspect you are having a non-2FA auth issue, the output of the following would be useful to diagnose the issue:

```sh
sudo journalctl --no-hostname _SYSTEMD_UNIT=NetworkManager.service + SYSLOG_IDENTIFIER=pppd
```
(Maybe replace any public IP address in the above output if you wish before posting)

**Comment by dkosovic** [comment]
As you are using the FortiClient on Windows, you'll probably have more luck with [NetworkManager-fortisslvpn](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn) which has native 2FA support and uses [openfortivpn](https://github.com/adrienverge/openfortivpn).

Sorry, there is no native 2FA support with NetworkManager-l2tp, basically the same as the built-in Windows L2TP client.

**Comment by pablogipi** [comment]
Sorry for the late response Douglas.
And thanks for your comments.
Unfortunately they are using FortiClient using IPSEC VPN, not the SSL.
After some more testing I wasn't sure if the client I have to use is l2tp or vpnc, both cases don't support 2FA.
The second factor is using FortiToken, but Iahevnt figure out yet how to introduce this second factor.
I have seen some people commenting you can add is after the user password separated by a comma, but still no luck.
It is strange that been 2FA so common this days Linux pretty much dont have support for it in NetworkManager.
Thanks for the help! And for the good work maintaining l2tp.
