### ISSUE TITLE
Link Error xl2tpd

### ISSUE THREAD

**Issue by Ronald-Cifuentes** [nm-l2tp/NetworkManager-l2tp#206]
there are aun error in xl2tpd ( https://www.xelerance.com/software/xl2tpd/ )

![image](https://user-images.githubusercontent.com/59535805/229891168-91401633-adcc-446a-9d5b-19c83ced5dea.png)

**Comment by dkosovic** [comment]
Thanks, xl2tpd web link updated in README.md.
