### ISSUE TITLE
Spell in the dialogues title L2TP

### ISSUE THREAD

**Issue by dilyanpalauzov** [nm-l2tp/NetworkManager-l2tp#212]
In the New connection and Edit connection dialogs, 
https://github.com/nm-l2tp/NetworkManager-l2tp/blob/main/appdata/l2tp.png , the software shall spell explicitly the type of VPN connection, irrespective of how the user named that connection.

I have created a NM-VPN connection and some months later I opened the edit-dialog and was wondering what NM-type the connection was.  The title of the dialog shall clarify this.

**Comment by dkosovic** [comment]
Sorry for my tardiness in responding.

The title bar in that screen shot along with the Apply and Cancel buttons aren't from this repository, you can confirm by opening [properties/nm-l2tp-dialog.ui](https://github.com/nm-l2tp/NetworkManager-l2tp/blob/main/properties/nm-l2tp-dialog.ui) file from this repository with the `glade` application. So I'm not able to control what is in the title bar.

With many NetworkManager VPN plug-ins, hovering of the gateway text box will tell you what type of VPN it is, unfortunately it isn't universal.

**Comment by dilyanpalauzov** [comment]
I see.  There are for sure some other ways to highlight in the dialog, apart from using its title bar, that the dialog is for L2TP connections.

**Comment by dkosovic** [comment]
The L2TP server tooltip and use L2TP ephemeral port checkbox should be enough to identify it as a L2TP vpn connection. In some user interfaces it is much more clearer as to the type of VPN connection it is before you even get to that dialog box.
