### ISSUE TITLE
Disconnected right after I opened connection

### ISSUE THREAD

**Issue by Kayxue** [nm-l2tp/NetworkManager-l2tp#219]
I want to connect to VPN through L2TP, but after I created configuration and open connection, it disconnected immediately after I opened connection in gnome setting. I run `systemctl status NetworkManager`, the terminal outputed these:
```
● NetworkManager.service - Network Manager
     Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; enabled; p
reset: disabled)
     Active: active (running) since Tue 2024-01-30 13:47:38 CST; 2min
 12s ago
       Docs: man:NetworkManager(8)
   Main PID: 414 (NetworkManager)
      Tasks: 4 (limit: 4548)
     Memory: 24.7M (peak: 35.1M)
        CPU: 548ms
     CGroup: /system.slice/NetworkManager.service
             └─414 /usr/bin/NetworkManager --no-daemon

Jan 30 13:48:32 Kay-UX31E NetworkManager[414]: <info>  [1706593712.9964] vpn[0x5
e0e8826c640,48f54ce2-6af8-40c1-af1f-bc2461e7cb7f,"VPN 1"]: starting l2tp
Jan 30 13:48:32 Kay-UX31E NetworkManager[414]: <info>  [1706593712.9969] audit: 
op="connection-activate" uuid="48f54ce2-6af8-40c1-af1f-bc2461e7cb7f" name="VPN 1
" pid=1818 uid=1000 result="success"
Jan 30 13:48:33 Kay-UX31E NetworkManager[414]: 
<warn>  [1706593713.0569] vpn[0x5e0e8826c640,48f54ce2-6af8-40c1-af1f-bc2461e7
cb7f,"VPN 1"]: secrets: failed to request VPN secrets #3: No agents were availab
le for this request.
```
Any idea about how to solve this?

System: Arch Linux
Place to created VPN settings and open connection: gnome-settings
Installed packages use to connect to l2tp: networkmanager, networkmanager-l2tp, strongswan, xl2tpd

**Comment by dkosovic** [comment]
GNOME uses Seahorse and KDE uses Kwallet for their secret service agents,  not sure about other desktop environments.
* https://wiki.archlinux.org/title/GNOME/Keyring
* https://wiki.archlinux.org/title/KDE_Wallet

**Comment by Kayxue** [comment]
Thanks, I have already solved this problem by manually installed networkmanager-l2tp-gnome deb package.
Idl why I could solved the problem like that...... but I hope that there will be a networkmanager-l2tp-gnome package for Arch Linux one day so we can solve the problem easier.
