### ISSUE TITLE
Use IKEv2 Key Exchange Checkbox in Debian Bookworm

### ISSUE THREAD

**Issue by indoctrine** [nm-l2tp/NetworkManager-l2tp#229]
Hello, this is a somewhat similar question to #62.

I have spent some time tonight setting up a connection to a VPN over IKEv2 with PSK + auth. I tried the suggested strongswan addon mentioned in the above issue on Debian however it does not provide any option for PSK as well as authentication. I spent a lot of time setting up the l2tp configuration in NetworkManager but it kept failing due to negotiating at IKEv1.

I tried on an Ubuntu machine and it had a checkbox for "Use IKEv2 Key Exchange" in the IPsec settings whereas Debian does not, but once I was able to check that, my VPN connection worked a treat. I was able to make it work on Debian by using `nmcli` to add `ipsec-ikev2 = yes` into the `vpn.data` section, however I now cannot touch my network settings window as it will overwrite my changes.

I'm unsure how the releases work for this or if I'm even in the right place, but would love to know if feature parity between Debian and Ubuntu is realistic or possible?

Thanks,
Beck

**Comment by dkosovic** [comment]
I think you are comparing either the GTK3 or GTK4 L2TP GUI plugins from this repository which have the option to another L2TP plugin from elsewhere, like the Qt L2TP plugin from plasm-nm and I believe Deepin Desktop has its own.

The following page shows the Debian and Ubuntu packages that use the source from this repository :
- https://tracker.debian.org/pkg/network-manager-l2tp

The Debian and Ubuntu packages are identical, the Ubuntu packages are unmodified from the corresponding Debian Sid packages at the time they were migrated from.

On either Debian or Ubuntu if you use GNOME Desktop (which uses Gnome Control Center), you'll be using the GTK4 L2TP GUI plugins from this repository. As mentioned previously, some other Desktop Environments might use other L2TP plugins from elsewhere, most use either the GTK4 or GTK3 ones from here.

NetworkManager-libreswan has IKEv2 support with PSK, but not one has created a Debian Ubuntu package for it.

**Comment by dkosovic** [comment]
Forgot to mention, Ubuntu derivatives like Lubuntu have issues as it is using the Qt6 based nm-tray and its manual recommends switching to the GTK3 based nm-applet when using VPNs:
- https://manual.lubuntu.me/stable/G/AdvancedNetworking.html

Kubuntu uses the Qt6 L2TP plugin as it unsurprisingly is using KDE plasma-nm.
